### ISSUE TITLE
Start up issue

### ISSUE THREAD

**Issue by Triumphhh** [bytedance/Jeddak-DPSQL#2]
Hello, I have a problem running `sh bootstrap.sh`. The program is running properly, but I can't access the site `http://127.0.0.1:5000`. It raises error `The requested URL was not found on the server`.  I have tried several methods but I still can't modify the default openning address of flask.

**Comment by abelkirito** [comment]
Hi, based on your description, the server is running successful, we don't have support get method for the route path "/", so you can't directly access http://127.0.0.1:5000. Please see the api doc https://github.com/bytedance/Jeddak-DPSQL/blob/master/doc/ZH/service_api.md, use api such as http://127.0.0.1:5000/api/v1/query.

**Comment by Triumphhh** [comment]
Thanks, this problem has been solved!
